---
# Set strict to true to turn warnings into errors to catch warnings within CI.
strict: false
theme:
  name: material
  # By default, fonts are pulled from Google on the Internet. To support offline usage, this is
  # disabled.
  font: false
  palette:
    scheme: slate
    primary: purple
    accent: blue
  icon:
    # GitHub specific.
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
extra_css:
  - static/stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GabDug/pdm-wheel
# This is needed to allow links to work when opened from the file system.
use_directory_urls: false
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_if_no_docstring: true
            show_signature_annotations: true
          import:
            - https://docs.python.org/3.10/objects.inv
  # Autodoc configuration.
  # https://mkdocstrings.github.io/recipes/#automatic-code-reference-pages
  # - gen-files:
  #     scripts:
  #       - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  # This plugin is used to validate URLs (including anchors).
  - git-revision-date
  - htmlproofer:
      # This is not enabled by default because this requires network I/O, so it is inherently not
      # exactly reproducible. For larger projects, this can also slow local build times.
      validate_external_urls: !ENV [HTMLPROOFER_VALIDATE_EXTERNAL_URLS, False]
      raise_error: true

site_name: pdm-wheel
copyright: Copyright &copy; 2023 Gabriel Dugny
# GitHub Specific Configuration.
repo_name: pdm-wheel
repo_url: https://github.com/GabDug/pdm-wheel
edit_uri: edit/main/docs/user_guide/docs/
nav:
  - index.md
  - Code Reference: reference/
